#!/usr/bin/env python
#-*-coding: utf-8-*-
# broadcast-ufc
# author: Isac C. 09/09/2016
import sys, os

message = raw_input("Type in a broadcast message: ")

class cores:
    lilas = '\033[95m'
    azul = '\033[94m'
    verd = '\033[92m'
    amar = '\033[93m'
    verm = '\033[91m'
    negr = '\033[1m'
    subl = '\033[4m'
    fim = '\033[0m'

def main():
    for i in range(1, 255):
        address = "200.129.39.%d" % i
        ping_cmd = "ping -c 1 -W 1 %s 2> /dev/null > /dev/null" % address
        if os.system(ping_cmd) == 0:
            print "%s %s is up... %s" % (cores.amar, address, cores.amar)

            # apt-get install sshpass
            ssh_cmd = "sshpass -p alunoufc ssh -o StrictHostKeyChecking=NO alunoufc@%s" % address

            remote_cmd1 = """ %s "echo '%s' > /tmp/null.txt " > /dev/null 2> /dev/null  """ % (ssh_cmd, message)

            if os.system(remote_cmd1) == 0:
                remote_cmd2 = """ %s 'wall < /tmp/null.txt > /dev/null 2> /dev/null' """ % ssh_cmd
                os.system(remote_cmd2)
                print  "%s Message sent to %s %s" % (cores.verd, address, cores.fim)
            else:
                print "%s Failed to ssh %s %s" % (cores.verm, address, cores.fim)

        else:
            print "%s %s is down... %s" % (cores.verm, address, cores.fim)

if __name__ == "__main__":
    try:
        main()
    except KeyBoardInterruptException:
        print cores.fim

